---
title: "heatmap"
author: "Sebastian Mølvang Dall"
date: '2022-08-10'
output: html_document
editor_options: 
  chunk_output_type: console
---

## Loading libraries

```{r}
library(tidyverse)
library(ggpubr)
library(mplibrary)
source("./functions/metadata_functions.R")
source("./functions/gg_functions.R")
```

## Loading Data

**Important!:The MicroPouchNP heatmap is in the bottom. Follow the headers**

```{r}
metadata <- load_metadata()

metaphlan <- read_delim(
    "../data/metaphlan/MetaPhlAn_4.1.0_Combined_NonHuman_Subsampled_2000000_profile.txt", 
    delim = "\t", 
    show_col_types = FALSE, 
    skip = 1
  ) %>% 
    filter_taxonomy("genus") %>% 
    remove_NonHuman_from_colnames()

t_metaphlan <- metaphlan %>%
        transposeMetaphlan()

project_filter <- "NP"
```

```{r}
metadata_in_metaphlan <- metadata %>%
  filter(sample_barcode %in% colnames(metaphlan))


metaphlan_long <- metaphlan %>%
  pivot_longer(-clade_name, names_to = "sample_barcode") %>%
  arrange(sample_barcode)
```

### Filtering for relevant patients and donors

Just as in alpha_beta_diversity.rmd, the donors are filtered such that only donors used for the available patients are used.

```{r}
stages <- stages_all

metadata_relevant <- isolateProjectMetadata(metadata_in_metaphlan, project_filter = "NP") %>%
  mutate(
    sample_group = paste0(group, "_", x_axis),
    sample_group = if_else(str_detect(sample_group, "FMT_Donor"), str_remove(sample_group, "FMT_"), sample_group)
  ) %>%
  filter(x_axis %in% stages)

n_genera <- 15
```

#### Adding taxonomy to metadata table

```{r}
metadata_relevant_with_tax <- left_join(metadata_relevant, metaphlan_long)
```

## heatmap visualization 
```{r}
metadata_tax_hellinger <- hellingerTransformSamples(metadata_relevant_with_tax)
top_genera_weighted <- calculateTopGenera(metadata_tax_hellinger %>% filter(clade_name != "UNCLASSIFIED"), n_genera = n_genera)
top_genera_weighted_arranged_by_donor <- arrangeTopGeneraInDonor(metadata_tax_hellinger, top_genera_weighted)
```


```{r}
plot_heatmap <- function(input){
  
  return(
    input %>% 
    ggplot(aes(x = x_axis, y = fct_rev(clade_name), fill = hellinger, label = value)) +
      geom_tile(color = "white") +
      scale_fill_gradient(low = "white", high = "red") +
      # geom_text(color = "black") +
      facet_grid(. ~ id, scales = "free_x", space = "free") +
      labs(x = "", y = "") +
      plot_theme +
      theme(
        axis.text.x = element_text(angle = 90, vjust = 0.35, hjust = 1),
        axis.text = element_text(size = 8),
        strip.text.x = element_text(size = 10),
      )
  )
}
```



```{r}
labels <- c("Pre", paste0("Day ", c(5, 10, 16, 28)), "Post", paste0("Follow-up ", c(1, 3, 6, 12), "M"), paste0("Donor_b", 1:12))
stages_withdonorbatch <- c(grep("Donor", stages, invert = T, value = T), paste0("Donor_b", 1:12))
labels_renamed <- c(stages_labels, paste0("Donor_b", 1:12)) 
labels_renamed <- grep("Donor$", labels_renamed, invert = T, value = T)

metadata_tax_hellinger %>%
  filter(clade_name %in% top_genera_weighted$clade_name) %>%
  mutate(
    clade_name = factor(clade_name, levels = top_genera_weighted_arranged_by_donor$clade_name),
    x_axis = if_else(x_axis == "Donor", paste0(x_axis, "_b", fecal_donation_number), x_axis),
    x_axis = factor(x_axis, levels = stages_withdonorbatch, labels = labels_renamed),
    value = if_else(value < 10, round(value, 1), floor(value)),
    id = factor(id, levels = c("pt001", "pt002", "pt006", "asym004"))
  ) %>%
  plot_heatmap()

ggsave("../figures/heatmap/heatmap_hellinger_alldonorbatches.png", device = "png", width = 20, height = 10)
```


```{r}
stages_labels[11] = "IPAA Donor"

hm <- metadata_tax_hellinger %>%
  filter(clade_name %in% top_genera_weighted$clade_name) %>%
  group_by(id, x_axis, clade_name) %>%
  summarise(hellinger = mean(hellinger),
            value = mean(value)) %>%
  mutate(
    clade_name = factor(clade_name, levels = top_genera_weighted_arranged_by_donor$clade_name),
    x_axis = factor(x_axis, levels = stages, labels = stages_labels),
    value = if_else(value < 10, round(value, 1), floor(value)),
    id = factor(id, c("Patient 1", "Patient 2", "Patient 3",""), levels = c("pt001", "pt002", "pt006", "asym004"))
  ) %>%
  plot_heatmap() +
  theme(
    legend.position = "right"
  )
hm
save(hm, file = "../figures/hm.RData")
ggsave("../figures/heatmap/heatmap_hellinger.png", device = "png", width = 15, height = 10)
```


### Treatment schema

```{r}
donorTreatment <- metadata_relevant %>%
  pivot_longer(batch_1:batch_3, names_to = "batch", values_to = "batch_number") %>%
  filter(!is.na(batch_number)) %>%
  select(id, x_axis, donor, batch, batch_number) %>%
  mutate(
    batch = str_replace(batch, "_", " "),
    x_axis = factor(x_axis, levels = stages_withdonorbatch, labels = labels)
  )


donorTreatment %>%
  ggplot(aes(x = batch, y = id, label = batch_number, group = id)) +
  geom_line() +
  geom_point(size = 10, color = "lightblue") +
  geom_text() +
  facet_grid(. ~ x_axis, scales = "free_x") +
  plot_theme +
  labs(y = "") +
  theme(panel.grid.major.x = element_blank())

ggsave("../figures/NP_donorbatch_treatment.png", device = "png")
```




